services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: tsroot
      POSTGRES_PASSWORD: tspassword
      POSTGRES_DB: ts-db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/tsdata

volumes:
  db_data:
